### ISSUE TITLE
Ручная реализация JWT-авторизации потенциально небезопасна

### ISSUE THREAD

**Issue by difhel** [MultiDragon/conduit-v11#1]
Предпочтительнее использовать готовую библиотеку pyjwt [ссылка](https://pypi.org/project/PyJWT/), тем более если для задачи проекта не нужен собственный протокол авторизации.

**Comment by Wizzerinus** [comment]
Python-jose != ручная реализация

https://github.com/Wizzerinus/conduit-v11/blob/9d4dd982f5b3ace558a39a75271c120fcec1a9be/Pipfile#L10

https://github.com/Wizzerinus/conduit-v11/blob/9d4dd982f5b3ace558a39a75271c120fcec1a9be/pyconduit/website/decorators.py#L53-L57

Если действительно есть какие-то проблемы с безопасностью (не отрицаю, хотя скорее всего нет), пиши в телеграм вместо issues (github не умеет в confidential issues)

**Comment by difhel** [comment]
Ага, похоже я слепой. Не там и не туда смотрел.
